HOTELS = [
    {
        "id": 1,
        "name": "Grand Palace Hotel",
        "city": "Hyderabad",
        "price_per_night": 3500,
        "rating": 4.7,
        "stars": 5,
        "amenities": ["wifi", "pool", "gym", "restaurant", "parking"],
        "available": True,
    },
    {
        "id": 2,
        "name": "Budget Inn",
        "city": "Hyderabad",
        "price_per_night": 1500,
        "rating": 4.1,
        "stars": 3,
        "amenities": ["wifi", "parking"],
        "available": True,
    },
    {
        "id": 3,
        "name": "Royal Residency",
        "city": "Bengaluru",
        "price_per_night": 4200,
        "rating": 4.8,
        "stars": 5,
        "amenities": ["wifi", "pool", "spa", "restaurant"],
        "available": True,
    },
    {
        "id": 4,
        "name": "City Comfort",
        "city": "Chennai",
        "price_per_night": 2300,
        "rating": 4.3,
        "stars": 4,
        "amenities": ["wifi", "gym", "parking"],
        "available": False,
    },
    {
        "id": 5,
        "name": "Sea View Resort",
        "city": "Goa",
        "price_per_night": 6200,
        "rating": 4.9,
        "stars": 5,
        "amenities": ["wifi", "pool", "beach", "restaurant", "spa"],
        "available": True,
    }
]